name: Compliance

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write

jobs:
  compliance:
    uses: depsdev/hot/.github/workflows/compliance.yml@main
